-- Seed every remaining country (world list), inactive by default except the 3 already active.
-- Existing rows (Canada, United States, France, Senegal, India, Philippines) are left untouched.
INSERT INTO countries (name, flag_emoji, currency_code, calling_code, active)
SELECT v.name, v.flag_emoji, v.currency_code, v.calling_code, v.active FROM (VALUES
    ('Afghanistan', '🇦🇫', 'AFN', '+93', false),
    ('Albania', '🇦🇱', 'ALL', '+355', false),
    ('Algeria', '🇩🇿', 'DZD', '+213', false),
    ('Andorra', '🇦🇩', 'EUR', '+376', false),
    ('Angola', '🇦🇴', 'AOA', '+244', false),
    ('Antigua and Barbuda', '🇦🇬', 'XCD', '+1', false),
    ('Argentina', '🇦🇷', 'ARS', '+54', false),
    ('Armenia', '🇦🇲', 'AMD', '+374', false),
    ('Australia', '🇦🇺', 'AUD', '+61', false),
    ('Austria', '🇦🇹', 'EUR', '+43', false),
    ('Azerbaijan', '🇦🇿', 'AZN', '+994', false),
    ('Bahamas', '🇧🇸', 'BSD', '+1', false),
    ('Bahrain', '🇧🇭', 'BHD', '+973', false),
    ('Bangladesh', '🇧🇩', 'BDT', '+880', false),
    ('Barbados', '🇧🇧', 'BBD', '+1', false),
    ('Belarus', '🇧🇾', 'BYN', '+375', false),
    ('Belgium', '🇧🇪', 'EUR', '+32', false),
    ('Belize', '🇧🇿', 'BZD', '+501', false),
    ('Benin', '🇧🇯', 'XOF', '+229', false),
    ('Bhutan', '🇧🇹', 'BTN', '+975', false),
    ('Bolivia', '🇧🇴', 'BOB', '+591', false),
    ('Bosnia and Herzegovina', '🇧🇦', 'BAM', '+387', false),
    ('Botswana', '🇧🇼', 'BWP', '+267', false),
    ('Brazil', '🇧🇷', 'BRL', '+55', false),
    ('Brunei', '🇧🇳', 'BND', '+673', false),
    ('Bulgaria', '🇧🇬', 'BGN', '+359', false),
    ('Burkina Faso', '🇧🇫', 'XOF', '+226', false),
    ('Burundi', '🇧🇮', 'BIF', '+257', false),
    ('Cabo Verde', '🇨🇻', 'CVE', '+238', false),
    ('Cambodia', '🇰🇭', 'KHR', '+855', false),
    ('Cameroon', '🇨🇲', 'XAF', '+237', false),
    ('Central African Republic', '🇨🇫', 'XAF', '+236', false),
    ('Chad', '🇹🇩', 'XAF', '+235', false),
    ('Chile', '🇨🇱', 'CLP', '+56', false),
    ('China', '🇨🇳', 'CNY', '+86', false),
    ('Colombia', '🇨🇴', 'COP', '+57', false),
    ('Comoros', '🇰🇲', 'KMF', '+269', false),
    ('Congo', '🇨🇬', 'XAF', '+242', false),
    ('Congo (DRC)', '🇨🇩', 'CDF', '+243', false),
    ('Costa Rica', '🇨🇷', 'CRC', '+506', false),
    ('Croatia', '🇭🇷', 'EUR', '+385', false),
    ('Cuba', '🇨🇺', 'CUP', '+53', false),
    ('Cyprus', '🇨🇾', 'EUR', '+357', false),
    ('Czechia', '🇨🇿', 'CZK', '+420', false),
    ('Côte d''Ivoire', '🇨🇮', 'XOF', '+225', false),
    ('Denmark', '🇩🇰', 'DKK', '+45', false),
    ('Djibouti', '🇩🇯', 'DJF', '+253', false),
    ('Dominica', '🇩🇲', 'XCD', '+1', false),
    ('Dominican Republic', '🇩🇴', 'DOP', '+1', false),
    ('Ecuador', '🇪🇨', 'USD', '+593', false),
    ('Egypt', '🇪🇬', 'EGP', '+20', false),
    ('El Salvador', '🇸🇻', 'USD', '+503', false),
    ('Equatorial Guinea', '🇬🇶', 'XAF', '+240', false),
    ('Eritrea', '🇪🇷', 'ERN', '+291', false),
    ('Estonia', '🇪🇪', 'EUR', '+372', false),
    ('Eswatini', '🇸🇿', 'SZL', '+268', false),
    ('Ethiopia', '🇪🇹', 'ETB', '+251', false),
    ('Fiji', '🇫🇯', 'FJD', '+679', false),
    ('Finland', '🇫🇮', 'EUR', '+358', false),
    ('Gabon', '🇬🇦', 'XAF', '+241', false),
    ('Gambia', '🇬🇲', 'GMD', '+220', false),
    ('Georgia', '🇬🇪', 'GEL', '+995', false),
    ('Germany', '🇩🇪', 'EUR', '+49', false),
    ('Ghana', '🇬🇭', 'GHS', '+233', false),
    ('Greece', '🇬🇷', 'EUR', '+30', false),
    ('Grenada', '🇬🇩', 'XCD', '+1', false),
    ('Guatemala', '🇬🇹', 'GTQ', '+502', false),
    ('Guinea', '🇬🇳', 'GNF', '+224', false),
    ('Guinea-Bissau', '🇬🇼', 'XOF', '+245', false),
    ('Guyana', '🇬🇾', 'GYD', '+592', false),
    ('Haiti', '🇭🇹', 'HTG', '+509', false),
    ('Honduras', '🇭🇳', 'HNL', '+504', false),
    ('Hungary', '🇭🇺', 'HUF', '+36', false),
    ('Iceland', '🇮🇸', 'ISK', '+354', false),
    ('Indonesia', '🇮🇩', 'IDR', '+62', false),
    ('Iran', '🇮🇷', 'IRR', '+98', false),
    ('Iraq', '🇮🇶', 'IQD', '+964', false),
    ('Ireland', '🇮🇪', 'EUR', '+353', false),
    ('Israel', '🇮🇱', 'ILS', '+972', false),
    ('Italy', '🇮🇹', 'EUR', '+39', false),
    ('Jamaica', '🇯🇲', 'JMD', '+1', false),
    ('Japan', '🇯🇵', 'JPY', '+81', false),
    ('Jordan', '🇯🇴', 'JOD', '+962', false),
    ('Kazakhstan', '🇰🇿', 'KZT', '+7', false),
    ('Kenya', '🇰🇪', 'KES', '+254', false),
    ('Kiribati', '🇰🇮', 'AUD', '+686', false),
    ('Kuwait', '🇰🇼', 'KWD', '+965', false),
    ('Kyrgyzstan', '🇰🇬', 'KGS', '+996', false),
    ('Laos', '🇱🇦', 'LAK', '+856', false),
    ('Latvia', '🇱🇻', 'EUR', '+371', false),
    ('Lebanon', '🇱🇧', 'LBP', '+961', false),
    ('Lesotho', '🇱🇸', 'LSL', '+266', false),
    ('Liberia', '🇱🇷', 'LRD', '+231', false),
    ('Libya', '🇱🇾', 'LYD', '+218', false),
    ('Liechtenstein', '🇱🇮', 'CHF', '+423', false),
    ('Lithuania', '🇱🇹', 'EUR', '+370', false),
    ('Luxembourg', '🇱🇺', 'EUR', '+352', false),
    ('Madagascar', '🇲🇬', 'MGA', '+261', false),
    ('Malawi', '🇲🇼', 'MWK', '+265', false),
    ('Malaysia', '🇲🇾', 'MYR', '+60', false),
    ('Maldives', '🇲🇻', 'MVR', '+960', false),
    ('Mali', '🇲🇱', 'XOF', '+223', false),
    ('Malta', '🇲🇹', 'EUR', '+356', false),
    ('Marshall Islands', '🇲🇭', 'USD', '+692', false),
    ('Mauritania', '🇲🇷', 'MRU', '+222', false),
    ('Mauritius', '🇲🇺', 'MUR', '+230', false),
    ('Mexico', '🇲🇽', 'MXN', '+52', false),
    ('Micronesia', '🇫🇲', 'USD', '+691', false),
    ('Moldova', '🇲🇩', 'MDL', '+373', false),
    ('Monaco', '🇲🇨', 'EUR', '+377', false),
    ('Mongolia', '🇲🇳', 'MNT', '+976', false),
    ('Montenegro', '🇲🇪', 'EUR', '+382', false),
    ('Morocco', '🇲🇦', 'MAD', '+212', false),
    ('Mozambique', '🇲🇿', 'MZN', '+258', false),
    ('Myanmar', '🇲🇲', 'MMK', '+95', false),
    ('Namibia', '🇳🇦', 'NAD', '+264', false),
    ('Nauru', '🇳🇷', 'AUD', '+674', false),
    ('Nepal', '🇳🇵', 'NPR', '+977', false),
    ('Netherlands', '🇳🇱', 'EUR', '+31', false),
    ('New Zealand', '🇳🇿', 'NZD', '+64', false),
    ('Nicaragua', '🇳🇮', 'NIO', '+505', false),
    ('Niger', '🇳🇪', 'XOF', '+227', false),
    ('Nigeria', '🇳🇬', 'NGN', '+234', false),
    ('North Korea', '🇰🇵', 'KPW', '+850', false),
    ('North Macedonia', '🇲🇰', 'MKD', '+389', false),
    ('Norway', '🇳🇴', 'NOK', '+47', false),
    ('Oman', '🇴🇲', 'OMR', '+968', false),
    ('Pakistan', '🇵🇰', 'PKR', '+92', false),
    ('Palau', '🇵🇼', 'USD', '+680', false),
    ('Panama', '🇵🇦', 'PAB', '+507', false),
    ('Papua New Guinea', '🇵🇬', 'PGK', '+675', false),
    ('Paraguay', '🇵🇾', 'PYG', '+595', false),
    ('Peru', '🇵🇪', 'PEN', '+51', false),
    ('Poland', '🇵🇱', 'PLN', '+48', false),
    ('Portugal', '🇵🇹', 'EUR', '+351', false),
    ('Qatar', '🇶🇦', 'QAR', '+974', false),
    ('Romania', '🇷🇴', 'RON', '+40', false),
    ('Russia', '🇷🇺', 'RUB', '+7', false),
    ('Rwanda', '🇷🇼', 'RWF', '+250', false),
    ('Saint Kitts and Nevis', '🇰🇳', 'XCD', '+1', false),
    ('Saint Lucia', '🇱🇨', 'XCD', '+1', false),
    ('Saint Vincent and the Grenadines', '🇻🇨', 'XCD', '+1', false),
    ('Samoa', '🇼🇸', 'WST', '+685', false),
    ('San Marino', '🇸🇲', 'EUR', '+378', false),
    ('Sao Tome and Principe', '🇸🇹', 'STN', '+239', false),
    ('Saudi Arabia', '🇸🇦', 'SAR', '+966', false),
    ('Serbia', '🇷🇸', 'RSD', '+381', false),
    ('Seychelles', '🇸🇨', 'SCR', '+248', false),
    ('Sierra Leone', '🇸🇱', 'SLE', '+232', false),
    ('Singapore', '🇸🇬', 'SGD', '+65', false),
    ('Slovakia', '🇸🇰', 'EUR', '+421', false),
    ('Slovenia', '🇸🇮', 'EUR', '+386', false),
    ('Solomon Islands', '🇸🇧', 'SBD', '+677', false),
    ('Somalia', '🇸🇴', 'SOS', '+252', false),
    ('South Africa', '🇿🇦', 'ZAR', '+27', false),
    ('South Korea', '🇰🇷', 'KRW', '+82', false),
    ('South Sudan', '🇸🇸', 'SSP', '+211', false),
    ('Spain', '🇪🇸', 'EUR', '+34', false),
    ('Sri Lanka', '🇱🇰', 'LKR', '+94', false),
    ('Sudan', '🇸🇩', 'SDG', '+249', false),
    ('Suriname', '🇸🇷', 'SRD', '+597', false),
    ('Sweden', '🇸🇪', 'SEK', '+46', false),
    ('Switzerland', '🇨🇭', 'CHF', '+41', false),
    ('Syria', '🇸🇾', 'SYP', '+963', false),
    ('Taiwan', '🇹🇼', 'TWD', '+886', false),
    ('Tajikistan', '🇹🇯', 'TJS', '+992', false),
    ('Tanzania', '🇹🇿', 'TZS', '+255', false),
    ('Thailand', '🇹🇭', 'THB', '+66', false),
    ('Timor-Leste', '🇹🇱', 'USD', '+670', false),
    ('Togo', '🇹🇬', 'XOF', '+228', false),
    ('Tonga', '🇹🇴', 'TOP', '+676', false),
    ('Trinidad and Tobago', '🇹🇹', 'TTD', '+1', false),
    ('Tunisia', '🇹🇳', 'TND', '+216', false),
    ('Turkey', '🇹🇷', 'TRY', '+90', false),
    ('Turkmenistan', '🇹🇲', 'TMT', '+993', false),
    ('Tuvalu', '🇹🇻', 'AUD', '+688', false),
    ('Uganda', '🇺🇬', 'UGX', '+256', false),
    ('Ukraine', '🇺🇦', 'UAH', '+380', false),
    ('United Arab Emirates', '🇦🇪', 'AED', '+971', false),
    ('United Kingdom', '🇬🇧', 'GBP', '+44', false),
    ('Uruguay', '🇺🇾', 'UYU', '+598', false),
    ('Uzbekistan', '🇺🇿', 'UZS', '+998', false),
    ('Vanuatu', '🇻🇺', 'VUV', '+678', false),
    ('Vatican City', '🇻🇦', 'EUR', '+379', false),
    ('Venezuela', '🇻🇪', 'VES', '+58', false),
    ('Vietnam', '🇻🇳', 'VND', '+84', false),
    ('Yemen', '🇾🇪', 'YER', '+967', false),
    ('Zambia', '🇿🇲', 'ZMW', '+260', false),
    ('Zimbabwe', '🇿🇼', 'ZWL', '+263', false)
) AS v(name, flag_emoji, currency_code, calling_code, active)
WHERE NOT EXISTS (SELECT 1 FROM countries c WHERE c.name = v.name);
